basnijholt/adaptive-lighting

- custom_components/adaptive_lighting/translations/de.json
> Added german translation

- README.md
I'd been scratching my head over this for a little bit when I realized that the optional value column had not been updated to reflect the description which clearly states it is optional.
> Update README.md set_manual_control

- custom_components/adaptive_lighting/translations/en.json
When installing this integration I found that some of the descriptions of the settings could be better. Also the formatting was very slightly inconsistent. 
Here is a suggestion for improved descriptions, if accepted I'll update the Swedish ones as well.
> Improvements to setting descriptions.

- custom_components/adaptive_lighting/translations/da.json
> i18n: Add Danish translation

- README.md
@RubenKelevra, is this good with you?
Go ahead and merge if you are ok with it 😄
> add Maintainers section

- custom_components/adaptive_lighting/switch.py
The aim here is to be able to trace why a light was turned on, even if `adaptive_lighting.apply` was used in the process. The `parent_id` of the `context` created by Adaptive Lighting will point to the original event (e.g. an automation trigger) that called `adaptive_lighting.apply` (or `adaptive_lighting.set_manual_control`).
Traces don't appear in the logbook because events aren't fired, but the contexts can be retrieved in automation templates (e.g. ``{{ trigger.to_state.context.parent_id }}`.
> Associate contexts with causing events/services via parent_id

- README.md
I forgot to commit the `README.md` change! My bad.
Signed-off-by: Avi Miller <me@dje.li>
> Update README.md to include sleep_transition

- custom_components/adaptive_lighting/switch.py
I wanted to use sunset after midnight but it didn't work out of the box. Turned out that the small fix to the noon and midnight calculation is enough to fix the problem.
#105
> Unconventional sunrise and sunset times

- custom_components/adaptive_lighting/switch.py
This fixes an issue where if the `adaptive_lighting.apply` service was called without the `lights` parameter and there is more than one instance of `adaptive_lighting` configured, it would use the lights of the first `adaptive_lighting` switch as the default, rather than the lights of the switch the service was called for.
Related PR where the default value for `lights` was introduced: #196
> Fix default lights for `adaptive_lighting.apply` service

- custom_components/adaptive_lighting/translations/nb.json
Norwegian (norsk bokmål) translation
> Norwegian translation

- custom_components/adaptive_lighting/switch.py
Fix for device_state_attributes warnings which began in release 2021.12.0b
> device_state_attributes warnings 2021.12.0b

- hacs.json
Add capitalized naming and removed underscore ( _ )
> Prettify integration name in HACS

- custom_components/adaptive_lighting/switch.py
- tests/test_switch.py
The test I added reproduces the real error.
The code in `switch.py` now handles events with `area_id`.
> Add support for areas and add a test that reproduce issue of #75 #283

- custom_components/adaptive_lighting/manifest.json
- custom_components/adaptive_lighting/switch.py
Addresses https://github.com/basnijholt/adaptive-lighting/issues/322.
> Take care of edge case where no area_id or entity_id in service_data

- custom_components/adaptive_lighting/manifest.json
- custom_components/adaptive_lighting/switch.py
> Take care of the turn_on_event not having registered an event for entity_id

- custom_components/adaptive_lighting/manifest.json
- custom_components/adaptive_lighting/switch.py
> Make sure that 'settings' dict is populated when switch is off

- custom_components/adaptive_lighting/translations/cs.json
Please add a Czech translation. Translated with love in collaboration with Jitka Kravcová.
> Adding a Czech translation

- .github/workflows/hassfest.yaml
- .github/workflows/pytest.yaml
- .gitignore
- custom_components/adaptive_lighting/manifest.json
- test_dependencies.py
- tests/test_switch.py
Pytest and hassfest should be fixed.
> Fix the broken tests

- custom_components/adaptive_lighting/switch.py
I would like to merge this before https://github.com/basnijholt/adaptive-lighting/pull/487
> Refactor find_switch_for_lights and more small refactors

- custom_components/adaptive_lighting/switch.py
Side effect of merging PRs
`include_config_in_attributes` code needs to go inside `set_changeable_settings` not init. otherwise change_switch_settings cant update that attribute correctly.
> Move include_config to set_changeable_settings

- custom_components/adaptive_lighting/services.yaml
Perhaps a method of auto-filling documentation to these files could be developed.
> Update services.yaml with `include_config_in_attributes`

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/doc.md
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/feature.md
As suggested here https://github.com/basnijholt/adaptive-lighting/pull/500#issuecomment-1493460673 by @th3w1zard1
> Update issue templates

- custom_components/adaptive_lighting/switch.py
- tests/test_switch.py
As requested by @mindtripper in https://github.com/basnijholt/adaptive-lighting/issues/525.
> Add auto_reset_time_remaining attribute

- custom_components/adaptive_lighting/switch.py
@th3w1zard1, I am still not sure whether what I did here is better. Give it a look over.
Perhaps it's worse. I will have a fresh look tomorrow!
> Possible refactor of _update_attrs_and_maybe_adapt_lights

- README.md
Ikea Tradfri lights have two known firmware quirks which result in unexpected behavior. Add config recommendations for AL to work around them.
References:
- https://github.com/Koenkk/zigbee2mqtt/issues/1810
- https://github.com/Koenkk/zigbee2mqtt/issues/4316
- https://www.reddit.com/r/tradfri/comments/au903n/firmware_bugs_in_ikea_bulbs/
> docs: Ikea light config recommendations

- custom_components/adaptive_lighting/manifest.json
- custom_components/adaptive_lighting/switch.py
@protyposis, this is what I mentioned here: https://github.com/basnijholt/adaptive-lighting/pull/628#issuecomment-1644046360
> Find adaptive_switch in TurnOnOffListener

- custom_components/adaptive_lighting/const.py
- custom_components/adaptive_lighting/switch.py
- tests/test_switch.py
@Tommatheussen, @tomadan1968, @Ede711, @cinghialino, @javilopezalarcon, @CmdrShepard482, @ASNNetworks, @asolochek, @dexn
Hopefully this fixes the issue you all reported in #611.
Could anyone give it a try?
> Revert supported_features from #565 and #575, fixes #601

- custom_components/adaptive_lighting/adaptation_utils.py
- custom_components/adaptive_lighting/switch.py
- tests/test_switch.py
Initial attempt to fix #645.
Not sure if I will have the time to further look into this problem ATM.
> Fix multiple switches controlling one light (reactive path)

- custom_components/adaptive_lighting/switch.py
When `transition` equals `interval`, or is just slightly shorter, it can happen that the next adaptation starts before the previous one has finished, resulting in an overlap. This isn't noticeable to users if lights implement transitions correctly (only Ikea lights during color changes are currently known to be problematic), but it manifests in a `Ongoing adaptation of <light> cancelled` debug log. The overlap has likely been there for a while, but the log has only been added recently in #590.
This is a quick fix that adds a constant processing overhead delay to the adaptation update interval to prevent the overlap in common cases. It's not the ultimate solution. In addition, the `send_split_delay` is now also considered. It also lead to overlaps when `transition + send_split_delay >= …
> fix: overlapping adaptations

- custom_components/adaptive_lighting/switch.py
- tests/test_switch.py
> With transition_until_sleep and sleep_rgb, after sunset, use RGB colors

- custom_components/adaptive_lighting/manifest.json
- custom_components/adaptive_lighting/switch.py
- tests/test_switch.py
I didn't realize that `percent` is between `-1` and `1`.
Therefore interpolation didn't work properly.
> Ensure that interpolation is in [0, 1], fixes #624

- custom_components/adaptive_lighting/adaptation_utils.py
- custom_components/adaptive_lighting/switch.py
@bcutter, this is a part of the flashing issue solution brought up in https://github.com/basnijholt/adaptive-lighting/issues/682#issuecomment-1657222508
> Mark as manually controlled when using flash, effect, or RGBW(W)

- custom_components/adaptive_lighting/switch.py
- tests/test_switch.py
This fixes the condition that is brought up in https://github.com/basnijholt/adaptive-lighting/issues/682#issue-1827870636 by @bouwew.
> Make sure that SimpleSwitches are added before AdaptiveSwitch

- custom_components/adaptive_lighting/switch.py
Closes #692, thanks for reporting @ejpenney!
> Require take_over_control for to ignore non-turn_on state off -> on event

- custom_components/adaptive_lighting/switch.py
@protyposis, what do you think about this change?
This was a problem brought up in https://github.com/basnijholt/adaptive-lighting/issues/622#issuecomment-1651077606.
> Do not update the call when calling light.turn_on with brightness=0

- custom_components/adaptive_lighting/switch.py
Closes #701.
Thanks to @mindtripper for reporting.
> Allow adaptive_lighting.apply to turn on lights and do not issue log message

- custom_components/adaptive_lighting/switch.py
- tests/test_switch.py
> Fix adaptive_lighting.change_switch_settings service

- custom_components/adaptive_lighting/const.py
- custom_components/adaptive_lighting/switch.py
> Fix min_sunrise_time and max_sunset_time

- custom_components/adaptive_lighting/switch.py
- tests/test_switch.py
Closes #723, see the error log there.
This adds a test that fails on main but passes now.
> Fix adapt_only_on_bare_turn_on and apply does not result in manual_control

- custom_components/adaptive_lighting/config_flow.py
- custom_components/adaptive_lighting/switch.py
Closes https://github.com/basnijholt/adaptive-lighting/issues/745
> Fix #745, first time YAML setup

- custom_components/adaptive_lighting/translations/de.json
- custom_components/adaptive_lighting/translations/fr.json
- custom_components/adaptive_lighting/translations/nl.json
This reverts commit 627c7a120c0ea54a9de6d881dd8ec896cb9dc145.
The automated translations are very bad...
> Revert "Translations update from Hosted Weblate (de, nl, fr) (#755)"

- README.md
> Add note about temporary settings when using `change_switch_settings`

- webapp/requirements.txt
> Fix webapp not loading

- custom_components/adaptive_lighting/manifest.json
> Added light dependencies

- tests/test_config_flow.py
Also see https://github.com/basnijholt/adaptive-lighting/pull/1159
> Skip broken test `test_changing_options_when_using_yaml`
