custom_components/adaptive_lighting/switch.py

White value is available as a channel for brightness. This adds the support for lights that use it, using the same calculated value as brightness.
Fixes #26

feat: add white value to service data

---

custom_components/adaptive_lighting/switch.py

Fixes #148
IKEA lights don't list rgb as color_mode, although the service call accepts rgb as attributes. This way, xy and hs are also recognized as color capable.

Add xy and hs as alternative color modes to detect color capabilities

---

custom_components/adaptive_lighting/switch.py

Currently, when a non-zero transition time is set, the current settings are calculated and applied using the transition time.  However, if long transition times are set (e.g. 30+ minutes), then this means that the lights will lag behind where they should be.  With this PR, the target settings are calculated for the end of the transition duration, which means that the lights will smoothly fade to the setting that they should be at by the time the transition ends.
The upshot is that you can manually alter light settings, and with a long transition time of 1-2 hours, they will retain the manual settings and gradually fade back to the auto settings.  This allows for temporary manual control with a smooth and pleasant user experience, with no need to detect external changes and cede or …

Calculate future settings to allow for long transition periods

---

custom_components/adaptive_lighting/services.yaml
custom_components/adaptive_lighting/switch.py

The apply service is meant to apply the adaptive lighting parameters to a specific set of light(s). This set of lights need to be passed to the service, even though each Adaptive Lighting switch already has this list configured on itself. While having the flexibility to apply to some, it also might be useful to apply to all lights that the switch manages.
This patch makes the lights paramater optional and defaults it to the lights configured on the corresponding configuration entry of the switch being called.

Default `lights` of the `apply` service

---

custom_components/adaptive_lighting/switch.py

Pylance said:
```
Tuple expression not allowed in type annotation
Use Tuple[T1, ..., Tn] to indicate a tuple type or Union[T1, T2] to indicate a union type
```

Fix tuple expression in type annotation

---

custom_components/adaptive_lighting/config_flow.py

When using the GUI to set options, if a light entity, which was previously configured, is no longer available, then it won't show up in the dropdown list, and causes the validation to fail.  
Validation fails with this error:
This failure means there is no way to de-select the light entity, or change any options under this condition.
This PR compares the list of configured lights, to the all_lights variable, and if any are missing, appends them to all_lights.  This allows the user to de-select the light, and make changes to the options.
Will resolve the following issues:
https://github.com/basnijholt/adaptive-lighting/issues/349
https://github.com/basnijholt/adaptive-lighting/issues/287
https://github.com/basnijholt/adaptive-lighting/issues/278

Fix missing light entities in options list 

---

.pre-commit-config.yaml

pre-commit: switch flake8 repo from gitlab to github

---

README.md

@basnijholt thank you for this repo!! I wanted to propose a small tweak to the readme. While implementing `adaptive_lighting.**apply**` in automations, I've noticed that listing the `lights` isn't required. For instance, if I have an adaptive lighting entity called `adaptive_lighting.office`, I can condition a motion sensor trigger with the following action successfully:
service: adaptive_lighting.apply
data:
entity_id: switch.adaptive_lighting_office
turn_on_lights: true

Updated optional status for lights in service

---

custom_components/adaptive_lighting/switch.py
tests/test_switch.py

Fixes #374.
See changes in https://github.com/home-assistant/core/pull/79591.
@pankrusheff

Use Kelvin instead of Mired, default since core=2022.11

---

Dockerfile

Set clone depth=1 to speedup the cloning of home-assistant/core

---

Dockerfile

Docker build is currently failing

Try installing extra deps such that bcrypt and cryptography can be installed in arm/v7

---

Dockerfile

This will run all the tests by default but also allow custom function calls.
For example:
```bash
docker run -v $(pwd):/app basnijholt/adaptive-lighting:latest tests/components/adaptive_lighting/test_switch.py::test_adaptive_lighting_time_zones_and_sun_settings
```
will only run the `test_adaptive_lighting_time_zones_and_sun_settings` test.
This also allows to pass in multiple command line arguments for pytest, such as filtering of the logs (@th3w1zard1). I will have to figure out how to do that exactly though.

Use ENTRYPOINT and CMD

---

.github/workflows/main-to-master-sync.yml

I renamed the default branch. I am adding this CI job to automatically sync back the changes to the master branch.

(master renames to main) Sync main branch to master

---

README.md
custom_components/adaptive_lighting/const.py
custom_components/adaptive_lighting/switch.py

Timers now get updated when using `change_switch_settings`
I changed the max number of seconds from 7 days to one year as in my opinion it's unnecessary to limit as I stated in the original PR but you're the boss 😄

Autoreset_Control_Time - small changes

---

custom_components/adaptive_lighting/const.py
custom_components/adaptive_lighting/switch.py
tests/test_switch.py

This PR ensures we aren't flying blind when it comes to the transitions and the non HA changes. I added a significant amount of tests and removed the lazy hacky methods I wrote earlier.
We now fire an event _exactly_ like home assistant would during a transition. right down to the context id which we also now test.
I also updated some of the tests to have the dependency property, as when there are many failures it was hard to know which test to debug first. Now if for example `test_attributes_have_changed` fails, the `test_significant_changes` won't run.

Create intentionally over-redundant `state_change` tests and fix #541

---

custom_components/adaptive_lighting/manifest.json
custom_components/adaptive_lighting/switch.py
tests/test_switch.py

Here I make sure that the context_ids are time orderable (conform the ULID standard), however, I keep the ":" chars in to identify our contexts.
We can deal with making it conform later.

Make sure context_id is 26 chars and partially conform to ULID standard (HA 2023.04 fix)

---

custom_components/adaptive_lighting/const.py
custom_components/adaptive_lighting/switch.py

This cleans up `_supported_features` just a tad to support #563
The variable `supported` is now a dictionary of supported attributes that can be used in a `light.turn_on` call.
I'm breaking up #563 into smaller parts as you requested last time :)
If you're wondering why I've imported all of the other color attributes (i.e. `ATTR_RGBWW_COLOR` etc) it's because I'd like to support these formats in the future.

Refactor `_supported_features`

---

.github/workflows/install_dependencies/action.yml
.github/workflows/pytest.yaml
custom_components/adaptive_lighting/__init__.py
test_dependencies.py

The `reload_configuration_yaml` function listens for the `hass.config.entry_updated` event which is triggered whenever a configuration file is updated. Once this event is triggered, `reload_configuration_yaml` is called and it uses the `hass.services.async_call` method to call the `homeassistant.check_config` service which checks the configuration for any errors.
By doing this, we ensure that the configuration is reloaded and checked for errors before the entry is updated. This means that the reloaded configuration will be passed to `async_setup_entry` when it is called.
Home Assistant already reloads the changes in `configuration.yaml` for us. Our `reload_configuration_yaml` function simply triggers a check of the configuration file and the loading of any updated configuration. We then …

Auto reload YAML config changes

---

custom_components/adaptive_lighting/switch.py

Cancel ongoing split adaptation commands when lights are turned off to avoid the delayed second half of the command to turn lights back on.
Fixes https://github.com/basnijholt/adaptive-lighting/issues/410#issuecomment-1539788096. There's still a race condition between turn-off and adaptation commands, so it doesn't entirely fix #410. It reduces the likelihood, though (I am testing it locally).

fix: lights unexpectedly turn back on after switch-off

---

.github/workflows/pytest.yaml
custom_components/adaptive_lighting/switch.py

HA 2023.6 handles adding of a list of entities differently, which breaks testing and reloading AL (updating settings and disabling/enabling the integration). Fix by changing the entity order so that the simple switches are initialized first.
Validated with HA `2023.6.1`.

fix: 2023.6 compatibility

---

custom_components/adaptive_lighting/__init__.py
custom_components/adaptive_lighting/adaptation_utils.py
custom_components/adaptive_lighting/hass_utils.py
custom_components/adaptive_lighting/switch.py
tests/test_hass_utils.py
tests/test_switch.py

Adapt `light.turn_on` service calls, that initially turn on a light, directly (called _proactive adaptation_ in code) by injecting brightness and color into the service call data payload. This makes lights immediately turn on with the correct adaptation settings. Resolves #594.
Traditionally, AL follows a _reactive adaptation_ approach, which reacts to state change events. This works fine in most cases, but can result in a noticeable adaptation delay when turning on a light (due to events not being instant, and due to various light hardware quirks). Example: Previously, a light might first turn on at 100% brightness before AL kicks in and adapts it down to 1%. Now it directly turns on at 1% brightness.
This only affects service calls which turn on lights that are off, i.e., the initial …

feat: service call adaptation

---

custom_components/adaptive_lighting/switch.py

This is not perse needed, however, because of the logging it is more accurate.

Only cancel ongoing adaptation calls if still running

---

custom_components/adaptive_lighting/switch.py

I didn't realize that setdefault always executes the default.

Do not create multiple AdaptiveLightingManager instances

---

custom_components/adaptive_lighting/manifest.json
custom_components/adaptive_lighting/switch.py

This prevents the problem described by @bcutter in https://github.com/basnijholt/adaptive-lighting/issues/682#issuecomment-1657222508.

Do not assert but issue a warning

---

README.md

1800 seconds is incorrectly described in a comment  as 15 minutes. Correctly convert 1800 seconds to half an hour.

bug: fix bug in comment in readme

---

custom_components/adaptive_lighting/switch.py

Should prevent this (I saw in my logs)
```
2023-08-02 21:49:56.516 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Detected an 'light.turn_off('['light.philips_go', 'light.bed_led', 'light.bamboo']', transition=10.0)' event with context.id='01H6WVP8RJF4JZ78SFD98YA0RG'
2023-08-02 21:49:56.637 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Detected an 'on' → 'off' event for 'light.bamboo' with context.id='01H6WVP8RJF4JZ78SFD98YA0RG'
2023-08-02 21:49:56.672 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Detected an 'on' → 'off' event for 'light.bed_led' with context.id='01H6WVP8RJF4JZ78SFD98YA0RG'
2023-08-02 21:49:56.747 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Detected an 'on' → 'off' event for 'light.philips_go' with …
```

Bail adapting if on event equals off event context

---

README.md

Add warning about Zigbee groups

---

custom_components/adaptive_lighting/switch.py

Prevent light.turn_on of light that was just turned off

---

webapp/app.py

Thanks to @danielbrunt57 for reporting [here](https://community.home-assistant.io/t/adaptive-lighting-automatically-adapts-the-brightness-and-color-of-your-lights-based-on-the-suns-temperature-but-stops-when-you-manually-make-a-change/257416/169).

Fix sleep_mode + sleep_rgb_or_color_temp == "color_temp" in webapp

---

custom_components/adaptive_lighting/switch.py

Addresses [change to HA core ](https://github.com/home-assistant/core/pull/101946) flagged in #832 which results in the following error:
```
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 1129, in _async_update_at_interval_action
await self._update_attrs_and_maybe_adapt_lights(
File "/config/custom_components/adaptive_lighting/switch.py", line 1442, in _update_attrs_and_maybe_adapt_lights
and await self.manager.significant_change(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/adaptive_lighting/switch.py", line 2461, in significant_change
changed = _attributes_have_changed(
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/adaptive_lighting/switch.py", line 726, in _attributes_have_changed
if …
```

Protect for None attributes after HA core change

---

README.md

I'm creating this PR simply because I wasn't sure if the `adaptive_lighting:` entry is a requirement to access the UI. The old `Configuration -> Integrations` now named `Settings -> Devices & Services` confused me. 
After reading this below, I'm unclear if it's possible to add configuration entries in the YAML and others via the UI. I'm used to see integrations either use either YAML or UI but never both at the same time. Per the wordings, it seems like it's possible to use both at the same time but likely making sure there's no collision, i.e. 2 identical names.
```
Configure an Adaptive Lighting component. Option names align with the YAML settings. If you've defined this entry in YAML, no options will appear here. For interactive graphs that demonstrate parameter effects, visit [this …
```

README.md - Add note to access frontend UI

---

custom_components/adaptive_lighting/switch.py

Remove 'run_immediately' which will be deprecated in version 2025.5
I removed 'run immediately' from the 'async_listen' and 'async_listen_once' calls since this argument will be deprecated in versions > 2025.5 as indicated in the debug LOG
```
Detected that custom integration 'adaptive_lighting' calls `async_listen` with run_immediately, which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/adaptive_lighting/switch.py, line 1665: self.hass.bus.async_listen(, please create a bug report at https://github.com/basnijholt/adaptive-lighting/issues
Detected that custom integration 'adaptive_lighting' calls `async_listen` with run_immediately, which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/adaptive_lighting/switch.py, line …
```

Remove deprecated 'run_immediately'

---

custom_components/adaptive_lighting/const.py

The [Validate with hassfest](https://github.com/basnijholt/adaptive-lighting/actions/workflows/hassfest.yaml) workflow is constantly failing since [Sep 26th](https://github.com/basnijholt/adaptive-lighting/actions/runs/11042957978) with the following error message:
```
[TRANSLATIONS] Invalid translations/en.json: the string should not contain leading or trailing spaces for dictionary value @ data['options']['step']['init']['data']['adapt_only_on_bare_turn_on']. Got 'adapt_only_on_bare_turn_on: When turning lights on initially. If set to `true`, AL adapts only if `light.turn_on` is invoked without specifying color or brightness. ❌🌈 This e.g., prevents adaptation when activating a scene. If `false`, AL adapts regardless of the presence of color or brightness in the initial `service_data`. …
```

Remove trailing space from string in const.py

---

custom_components/adaptive_lighting/const.py
custom_components/adaptive_lighting/strings.json
custom_components/adaptive_lighting/translations/en.json

Sorry, [my previous PR](https://github.com/basnijholt/adaptive-lighting/pull/1146) didn't fix the issue with the failing workflows, as I removed the trailing space from the wrong place... 😅
Now I fixed it and removed the right one(s). I had to touch translation JSONs, and I'm not sure if they can be edited directly, or it will cause problems with Weblate.
Update: as you can see, now [the workflow now really succeeds](https://github.com/basnijholt/adaptive-lighting/actions/runs/12574528435/job/35048621799?pr=1148)!

Fix trailing spaces in const.py: restore correct one, remove incorrect one

---

custom_components/adaptive_lighting/__init__.py
custom_components/adaptive_lighting/strings.json

Change async_setup_entry to use await hass.config_entries.async_forward_entry_setups(config_entry, PLATFORMS)
Fixes https://github.com/basnijholt/adaptive-lighting/issues/1020

fix: async entry setup

---

custom_components/adaptive_lighting/config_flow.py

Fixes
`FAILED tests/components/adaptive_lighting/test_config_flow.py::test_incorrect_options - RuntimeError: Detected that integration 'adaptive_lighting' sets option flow config_entry explicitly, which is deprecated at homeassistant/components/adaptive_lighting/config_flow.py, line 86: self.config_entry = config_entry. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+adaptive_lighting%22`

Fix setting config_entry directly in ≥2024.12
